name: dev-mac

on: [ workflow_dispatch ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup build identity
        env:
          BUILD_CERT_BASE64: ${{ secrets.DEV_CERT_BASE64 }}
          BUILD_CERT_PASS: ${{ secrets.DEV_CERT_PASS }}
          DEV_ID_CERT_BASE64: ${{ secrets.DEV_ID_CERT_BASE64 }}
          DEV_ID_CERT_PASS: ${{ secrets.DEV_ID_CERT_PASS }}
          MAC_INSTALLER_CERT_BASE64: ${{ secrets.MAC_INSTALLER_CERT_BASE64 }}
          MAC_INSTALLER_CERT_PASS: ${{ secrets.MAC_INSTALLER_CERT_PASS }}
          BUILD_PROVISIONING: ${{ secrets.DEV_PROVISIONING }}
          BUILD_MAC_PROVISIONING: ${{ secrets.BUILD_MAC_PROVISIONING }}
          DEV_ID_PROVISIONING: ${{ secrets.DEV_ID_PROVISIONING }}
          KEYCHAIN_PASS: ${{ secrets.DEV_KEYCHAIN_PASS }}
        run: ./setup-build-identity.sh

      - name: Setup auth key
        env:
          APPSTORE_AUTH_KEY_BASE64: ${{ secrets.APPSTORE_AUTH_KEY_BASE64 }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys/
          AUTH_KEY_PATH=~/.appstoreconnect/private_keys/AuthKey_$APPSTORE_API_KEY.p8
          echo -n "$APPSTORE_AUTH_KEY_BASE64" | base64 --decode --output $AUTH_KEY_PATH

      - name: Set build number
        run: |
          tag=$(git describe --tags --abbrev=0)
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${tag#*-}" "sama/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.run_number }}" "sama/Info.plist"

      - name: Set environment
        run: ./set-env.sh dev

      - name: Cache SPM
        uses: actions/cache@v2
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('sama.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      - name: Build and distribute
        env:
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
          APPSTORE_API_ISSUER: ${{ secrets.APPSTORE_API_ISSUER }}
        run: ./build-distribute-mac.sh

      - name: Send zip to slack
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          APPSTORE_API_ISSUER: ${{ secrets.APPSTORE_API_ISSUER }}
        run: |
          #!/bin/bash
          curl \
           -F file=@build-sama/Sama.zip \
           -F "initial_comment=Sama mac app ${tag#*-} (${{ github.run_number }})" \
           -F channels=C02M9MAF7B5 \
           -H "Authorization: Bearer $SLACK_API_TOKEN" \
           https://slack.com/api/files.upload
