name: dev

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and distribute
        run: ./build-distribute.sh
