name: testddl

on:
  push:
    branches: [ test-ddl ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1

      - name: Setup build identity
        env:
          BUILD_CERT_BASE64: ${{ secrets.PROD_CERT_BASE64 }}
          BUILD_CERT_PASS: ${{ secrets.PROD_CERT_PASS }}
          BUILD_PROVISIONING: ${{ secrets.PROD_PROVISIONING }}
          KEYCHAIN_PASS: ${{ secrets.PROD_KEYCHAIN_PASS }}
        run: ./setup-build-identity.sh

      - name: Setup auth key
        env:
          APPSTORE_AUTH_KEY_BASE64: ${{ secrets.APPSTORE_AUTH_KEY_BASE64 }}
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
        run: |
          mkdir -p ~/.appstoreconnect/private_keys/
          AUTH_KEY_PATH=~/.appstoreconnect/private_keys/AuthKey_$APPSTORE_API_KEY.p8
          echo -n "$APPSTORE_AUTH_KEY_BASE64" | base64 --decode --output $AUTH_KEY_PATH

      - name: Set build number
        run: |
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString 1.1.1" "sama/Info.plist"
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion ${{ github.run_number }}" "sama/Info.plist"

      - name: Set environment
        run: ./set-env.sh prod

      - name: Build and distribute
        env:
          EXPORT_OPTIONS_PLIST: "env/prod/exportOptions.plist"
          APPSTORE_API_KEY: ${{ secrets.APPSTORE_API_KEY }}
          APPSTORE_API_ISSUER: ${{ secrets.APPSTORE_API_ISSUER }}
        run: ./build-distribute.sh
